### PR TITLE
Adding brand support

### PR DESCRIPTION
**Pull request by gustavoalmeida**
This PR adds support for brand value in the request translation methods

### CODE REVIEW

**Comment by andreffs18** [comment]
@gustavoalmeida can you add a simple test to verify that the new field is working as expected?

**Comment by gustavoalmeida** [comment]
Hey @andreffs18 ,

I added mock in the tests and the brand verifier as well

**Comment by hugofvs** [comment]
@gustavoalmeida you need to update the setup.py with the new version.

**Comment by gustavoalmeida** [comment]
> @gustavoalmeida you need to update the setup.py with the new version.

Hi @hugofvs , It is Done

**Pull request merged**
